import type { Metadata } from "next";
import { Space_Grotesk, Inter } from "next/font/google";
import Script from "next/script";
import "@/styles/globals.css";
import NavWrapper from "@/components/navbar/NavWrapper";
import SmoothScroll from "@/components/ui/SmoothScroll";
import BackToTop from "@/components/ui/BackToTop";
import MouseEffect from "@/components/ui/MouseEffect";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-space-grotesk",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-inter",
  display: "swap",
});

const SITE_URL = "https://www.sakib.app";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Abdullah Nazmus Sakib | Software Engineer",
    template: "%s | Abdullah Nazmus Sakib",
  },
  description:
    "Software engineer building enterprise web systems, clean APIs, and interfaces that hold up in production. Specializing in Angular, Node.js, and PostgreSQL.",
  keywords: [
    "Abdullah Nazmus Sakib",
    "Software Engineer",
    "Full Stack Developer",
    "Angular Developer",
    "Node.js Developer",
    "PostgreSQL",
    "TypeScript",
    "Hapi.js",
    "Bangladesh",
    "Portfolio",
    "Web Development",
    "Enterprise Web Systems",
    "Fintech Software",
  ],
  authors: [{ name: "Abdullah Nazmus Sakib", url: SITE_URL }],
  creator: "Abdullah Nazmus Sakib",
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: "Abdullah Nazmus Sakib",
    title: "Abdullah Nazmus Sakib | Software Engineer",
    description:
      "Software engineer building enterprise web systems, clean APIs, and interfaces that hold up in production.",
    // og:image is generated by app/opengraph-image.tsx (1200×630).
  },
  twitter: {
    card: "summary_large_image",
    title: "Abdullah Nazmus Sakib | Software Engineer",
    description:
      "Software engineer building enterprise web systems, clean APIs, and interfaces that hold up in production.",
    // twitter:image falls back to the generated opengraph-image.
  },
  icons: {
    icon: "/favicon.svg",
    shortcut: "/favicon.svg",
    apple: "/favicon.svg",
  },
  alternates: {
    canonical: SITE_URL,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} ${inter.variable}`}
      data-scroll-behavior="smooth"
      suppressHydrationWarning
    >
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        {/* Load the icon font without blocking first paint (improves LCP).
            media="print" makes it non-render-blocking; the script below
            promotes it to all screens once parsed. */}
        <link
          id="icon-font"
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap"
          media="print"
        />
        <noscript>
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap"
          />
        </noscript>
      </head>
      <body className="bg-background text-on-surface selection:bg-primary/30 min-h-screen overflow-x-hidden soft-grid antialiased" suppressHydrationWarning>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@graph": [
                {
                  "@type": "Person",
                  "@id": `${SITE_URL}/#person`,
                  name: "Abdullah Nazmus Sakib",
                  url: SITE_URL,
                  image: `${SITE_URL}/abdullah_nazmus_sakib.png`,
                  jobTitle: "Software Engineer",
                  description:
                    "Software engineer building enterprise web systems, clean APIs, and interfaces that hold up in production. Angular, Node.js, and PostgreSQL.",
                  address: {
                    "@type": "PostalAddress",
                    addressLocality: "Dhaka",
                    addressCountry: "BD",
                  },
                  worksFor: {
                    "@type": "Organization",
                    name: "Celloscope Limited",
                  },
                  alumniOf: {
                    "@type": "CollegeOrUniversity",
                    name: "Daffodil International University",
                  },
                  knowsAbout: [
                    "Angular",
                    "Next.js",
                    "Node.js",
                    "PostgreSQL",
                    "TypeScript",
                    "React",
                    "Hapi.js",
                    "Express.js",
                  ],
                  sameAs: [
                    "https://github.com/sakib963",
                    "https://linkedin.com/in/abdullahnazmussakib",
                  ],
                },
                {
                  "@type": "WebSite",
                  "@id": `${SITE_URL}/#website`,
                  url: SITE_URL,
                  name: "Abdullah Nazmus Sakib",
                  description:
                    "Portfolio of Abdullah Nazmus Sakib — software engineer specializing in Angular, Node.js, and PostgreSQL.",
                  inLanguage: "en",
                  publisher: { "@id": `${SITE_URL}/#person` },
                },
              ],
            }),
          }}
        />
        <Script id="icon-font-swap" strategy="afterInteractive">
          {`(function(){var l=document.getElementById('icon-font');if(l){if(l.sheet){l.media='all'}else{l.addEventListener('load',function(){l.media='all'})}}})();`}
        </Script>
        <Script id="theme-init" strategy="beforeInteractive">
          {`(function(){try{var t=localStorage.getItem('theme');var d=window.matchMedia('(prefers-color-scheme: dark)').matches;if(t==='dark'||(t===null&&d)){document.documentElement.classList.add('dark')}else{document.documentElement.classList.remove('dark')}}catch(e){}})();`}
        </Script>
        <SmoothScroll>
          <MouseEffect />
          <NavWrapper />
          {children}
          <BackToTop />
        </SmoothScroll>
      </body>
    </html>
  );
}
